### PR TITLE
Calculate actions correctly

### PR DESCRIPTION
**Pull request by Anton-Shutik**
Did small changes to `get_actions` method.
It will hide and disable "delete" action if user has no delete permission.
It will show all actions if user has "change" permission.
It will show no actions if user has not "change" permission

### CODE REVIEW

**Comment by Anton-Shutik** [comment]
@lefterisnik would you mind taking a look pls ?

**Comment by Anton-Shutik** [comment]
@lefterisnik thanks a lot. Would you mind release it to pypi with minor version (1.7.1 for example) change ?

**Comment by lefterisnik** [comment]
@Anton-Shutik done.

**Comment by Anton-Shutik** [comment]
thanks a lot

**Pull request merged**
